apiVersion: v1
version: 0.0.1
appVersion: v4.0.0-beta
name: blockscout
description: Blockscout monitoring
keywords:
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - pegasys
  - consensys
  - blockscout
home: https://docs.blockscout.com
sources:
  - https://github.com/blockscout/blockscout
maintainers:
  - name: Joshua Fernandes
    email: joshua.fernandes@consensys.net
  - name: Eric Lin
    email: eric.lin@consensys.net
icon: http://besu.hyperledger.org/en/latest/favicon.ico
dependencies:
  - name: postgresql
    version: "10.14.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled