apiVersion: v1
version: 0.0.1
appVersion: latest
name: goquorum-genesis
description: Quorum Genesis generator with Helm chart in Kubernetes
keywords:
  - geth
  - goquorum
  - ethereum
  - quorum
  - enterprise
  - blockchain
  - pegasys
  - consensys
home: https://consensys.net/quorum/
sources:
  - https://consensys.net/quorum/
maintainers:
  - name: Joshua Fernandes
    email: joshua.fernandes@consensys.net
