---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goquorum-genesis.name" . }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "goquorum-genesis.name" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "goquorum-genesis.chart" . }}
    app.kubernetes.io/name: {{ include "goquorum-genesis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "list", "update", "delete", "patch" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "goquorum-genesis.name" . }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "goquorum-genesis.name" . }}-role
subjects:
  - kind: ServiceAccount
{{- if and (eq .Values.cluster.provider "aws") (.Values.cluster.cloudNativeServices) }}
    name: {{ .Values.aws.serviceAccountName }}
{{- else }}
    name: {{ include "goquorum-genesis.name" . }}-sa
{{- end }}
    namespace: {{ .Release.Namespace }}

