apiVersion: v1
version: 0.1.0
appVersion: 0.1.0
name: besu-minikube
description: Besu nodes for a POA network
keywords:
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - pegasys
  - consensys
home: https://besu.hyperledger.org
sources:
  - https://github.com/hyperledger/besu
maintainers:
  - name: Joshua Fernandes
    email: joshua.fernandes@consensys.net
icon: http://besu.hyperledger.org/en/latest/favicon.ico
dependencies:
  - name: besu-genesis
    repository: "file://charts/besu-genesis"
    version: 0.1.0
    alias: genesis
  - name: besu-node
    repository: "file://charts/besu-node"
    version: 0.1.0
    alias: validator-1
  - name: besu-node
    repository: "file://charts/besu-node"
    version: 0.1.0
    alias: validator-2
  - name: besu-node
    repository: "file://charts/besu-node"
    version: 0.1.0
    alias: validator-3
  - name: besu-node
    repository: "file://charts/besu-node"
    version: 0.1.0
    alias: validator-4
  - name: blockscout
    repository: "file://charts/blockscout"
    version: 0.1.0
    alias: blockscout

