{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "besu-node.fullname" . }}-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.azure.nodePoolIdentityClientId }}"
    keyvaultName: "{{ .Values.azure.keyvaultName }}"
    tenantId: "{{ .Values.azure.tenantId }}"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: {{ include "besu-node.fullname" . }}-nodekey
          objectAlias: nodekey
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ include "besu-node.fullname" . }}-nodekeypub
          objectAlias: nodekey.pub
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ include "besu-node.fullname" . }}-enode
          objectAlias: enode
          objectType: secret
          objectVersion: ""
      {{- if .Values.quorumFlags.privacy }}
        - |
          objectName: {{ include "besu-node.fullname" . }}-tmkey
          objectAlias: tm.key
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ include "besu-node.fullname" . }}-tmkeypub
          objectAlias: tm.pub
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ include "besu-node.fullname" . }}-tmpassword
          objectAlias: tm.password
          objectType: secret
          objectVersion: ""
      {{- end }}
{{- end }}