---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "besu-node.fullname" . }}-pre-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "hook-succeeded"
  labels:
{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
    azure.workload.identity/use: "true"
{{- end }}
    app.kubernetes.io/name: pre-delete-hook
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels:
{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
        azure.workload.identity/use: "true"
{{- end}}
        app.kubernetes.io/name: pre-delete-hook
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
      serviceAccountName: {{ .Values.azure.serviceAccountName }}
{{- else if and (eq .Values.cluster.provider "aws") (.Values.cluster.cloudNativeServices) }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}
{{- else }}
      serviceAccountName: {{ include "besu-node.fullname" . }}-hooks-sa
{{- end }}
      restartPolicy: "OnFailure"
      containers:
        - name: {{ template "besu-node.fullname" . }}-node-pre-delete-hook
          image: "{{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}"
          imagePullPolicy: {{ .Values.image.hooks.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - |

              echo "{{ template "besu-node.fullname" . }} Pre Delete hook ..."

{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}

              function deleteSecret {
                key=$1
                fpath=$2
                az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key > /dev/null 2>&1
                if [ $? -eq 0 ]; then
                  az keyvault secret delete --vault-name {{ .Values.azure.keyvaultName }} --name $key
                fi
              }

              az login --identity --debug
              az account set --subscription {{ .Values.azure.subscriptionId }}

{{- else if and (eq .Values.cluster.provider "aws") (.Values.cluster.cloudNativeServices) }}

              function deleteSecret {
                key=$1
                aws secretsmanager describe-secret --secret-id $key > /dev/null 2>&1
                if [ $? -eq 0 ]; then
                  aws secretsmanager delete-secret --secret-id $key --recovery-window-in-days 7
                fi
              }

{{- else }}

              function deleteSecret {
                key=$1
                kubectl delete secret ${key} --namespace {{ .Release.Namespace }}
              }

{{- end }}

              function delete_node_from_tessera_peers_configmap {
                kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o json
                # if there is no configmap, do nothing
                if [ $? -ne 0 ]; then
                  echo "No tessera-peers found, nothing to do..."
                # delete the one
                else
                  echo "tessera-peers found, deleting {{ template "besu-node.fullname" . }}..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o jsonpath='{.data.tesseraPeers}' ) > /tmp/tessera-peers.raw
                  cat /tmp/tessera-peers.raw | jq --arg NEEDLE "{{ template "besu-node.fullname" . }}" 'del(.[] | select( .url | contains($NEEDLE) ))' > /tmp/tessera-peers
                  kubectl -n {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers -o yaml --dry-run=client | kubectl replace -f -
                fi
              }

              function delete_node_from_enodes_configmap {
                kubectl -n {{ .Release.Namespace }}  get configmap besu-peers -o json
                # if there is no configmap, do nothing
                if [ $? -ne 0 ]; then
                  echo "No peers found, nothing to do..."
                # delete the one
                else
                  echo "besu-peers found, deleting {{ template "besu-node.fullname" . }}..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap besu-peers -o jsonpath='{.data.static-nodes\.json}' ) > /tmp/static-nodes.json.raw
                  cat /tmp/static-nodes.json.raw | jq --arg NEEDLE "{{ template "besu-node.fullname" . }}" 'del(.[] | select( . | contains($NEEDLE) ))' > /tmp/static-nodes.json
                  kubectl -n {{ .Release.Namespace }} create configmap besu-peers --from-file=static-nodes.json=/tmp/static-nodes.json -o yaml --dry-run=client | kubectl replace -f -

                  echo "Deleting node address configmap... "
                  kubectl delete configmap {{ template "besu-node.fullname" . }}-address --namespace {{ .Release.Namespace }}
                fi
              }


              function delete_node_from_besu_bootnodes_configmap {
                kubectl -n {{ .Release.Namespace }}  get configmap besu-bootnodes -o json
                # if there is no configmap, do nothing
                if [ $? -ne 0 ]; then
                  echo "No bootnodes found, nothing to do..."
                # delete the one
                else
                  echo "besu-bootnodes found, deleting {{ template "besu-node.fullname" . }}..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap besu-bootnodes -o jsonpath='{.data.bootnodes-json}' ) > /tmp/besu-bootnodes-json.raw
                  cat /tmp/besu-bootnodes-json.raw | jq --arg NEEDLE "{{ template "besu-node.fullname" . }}" 'del(.[] | select( . | contains($NEEDLE) ))' > /tmp/besu-bootnodes-json
                  cat /tmp/besu-bootnodes-json | jq -r -c '. | join(",")' | tr -d '\n' > /tmp/besu-bootnodes-string
                  kubectl -n {{ .Release.Namespace }} create configmap besu-bootnodes --from-file=bootnodes-json=/tmp/besu-bootnodes-json --from-file=bootnodes-string=/tmp/besu-bootnodes-string -o yaml --dry-run=client | kubectl replace -f -
                fi
              }

              delete_node_from_enodes_configmap
              delete_node_from_besu_bootnodes_configmap
              delete_node_from_tessera_peers_configmap

{{- if .Values.quorumFlags.removeKeysOnDelete }}

{{- if and (ne .Values.cluster.provider "local") (.Values.cluster.cloudNativeServices) }}

              deleteSecret {{ template "besu-node.fullname" . }}-nodekey
              deleteSecret {{ template "besu-node.fullname" . }}-nodekeypub
              deleteSecret {{ template "besu-node.fullname" . }}-enode
              deleteSecret {{ template "besu-node.fullname" . }}-accountPrivateKey
              deleteSecret {{ template "besu-node.fullname" . }}-accountPassword
              deleteSecret {{ template "besu-node.fullname" . }}-accountKeystore
              deleteSecret {{ template "besu-node.fullname" . }}-accountAddress
              deleteSecret {{ template "besu-node.fullname" . }}-address

{{- if .Values.quorumFlags.privacy }}
              deleteSecret {{ template "besu-node.fullname" . }}-tmkey
              deleteSecret {{ template "besu-node.fullname" . }}-tmkeypub
              deleteSecret {{ template "besu-node.fullname" . }}-tmpassword
{{- end }}

{{- else }}
              deleteSecret {{ template "besu-node.fullname" . }}-keys
              deleteSecret {{ template "besu-node.fullname" . }}-account
{{- if .Values.quorumFlags.privacy }}
              deleteSecret {{ template "besu-node.fullname" . }}-tessera-keys
{{- end }}

{{- end }}

{{- end }}

              echo "Completed"
