# Default values for genesys.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: pegasyseng/pantheon
  tag: develop
  # Always | IfNotPresent
  pullPolicy: IfNotPresent

validators:
  generated: true

# the values here are from the example config file found in the the [Quickstart](https://docs.pantheon.pegasys.tech/en/stable/Tutorials/Create-IBFT-Network/)
config:
  genesis:
    config:
      chainId: 1981
      constantinoplefixblock: 0
      ibft2:
        blockperiodseconds: 2
        epochlength: 30000
        requesttimeoutseconds: 10
    nonce: '0x0'
    timestamp: '0x58ee40ba'
    extraData: '0xf87ea00000000000000000000000000000000000000000000000000000000000000000f85494ca6e9704586eb1fb38194308e2192e43b1e1979c94ce2276efc33fee3c321e634eac28a9476e53b71c94f466a7174230056004d11178d2647c12740fa58b94b83820d6cf4b7e5aa67a2b57969caa5cdf6dff49808400000000c0'
    gasLimit: '0x47b760'
    difficulty: '0x1'
    mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
    coinbase: '0x0000000000000000000000000000000000000000'
    alloc:
      627306090abaB3A6e1400e9345bC60c78a8BEf57:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
      f17f52151EbEF6C7334FAD080c5704D77216b732:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
  blockchain:
    nodes:
      generate: true
      count: 4
#      keys:
#        - "0xb295c4242fb40c6e8ac7b831c916846050f191adc560b8098ba6ad513079571ec1be6e5e1a715857a13a91963097962e048c36c5863014b59e8f67ed3f667680",
#        - "0x6295c4242fb40c6e8ac7b831c916846050f191adc560b8098ba6ad513079571ec1be6e5e1a715857a13a91963097962e048c36c5863014b59e8f67ed3f667680"
