---

quorumFlags:
  privacy: false
  removeKeysOnDelete: false

cluster:
  provider: local  # choose from: local | aws | azure
  cloudNativeServices: false # set to true to use Cloud Native Services (SecretsManager and IAM for AWS; KeyVault & Managed Identities for Azure)
  reclaimPolicy: Delete # set to either Retain or Delete

aws:
  # the aws cli commands uses the name 'quorum-sa' so only change this if you altered the name
  serviceAccountName: quorum-sa
  # the region you are deploying to
  region: ap-southeast-2

azure:
  serviceAccountName: quorum-sa
  # the clientId of the user assigned managed identity created in the template
  identityClientId: azure-clientId
  keyvaultName: azure-keyvault
  # the tenant ID of the key vault
  tenantId: azure-tenantId
  # the subscription ID to use - this needs to be set explicitly when using multi tenancy
  subscriptionId: azure-subscriptionId

storage:
  sizeLimit: "20Gi"
  pvcSizeLimit: "20Gi"
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Delete" # choose from: Delete | Retain 
  aws:
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: gp3
      fsType: ext4

node:
  goquorum:
    resources:
      cpuLimit: 1
      cpuRequest: 0.1
      memLimit: "2G"
      memRequest: "1G"
    # privKey:
    # pubKey:
    dataPath: "/data/quorum"
    keysPath: "/keys"
    genesisFilePath: "/etc/genesis/genesis.json"
    customLabels: {}
    networkId: 10
    replicaCount: 1
    account:
      unlock: 0
      password: 'password'
      passwordPath: "/keys/accountPassword"
    log:
      verbosity: 5
    miner:
      threads: 1
      blockPeriod: 5
    p2p:
      enabled: true
      addr: "0.0.0.0"
      port: 30303
    rpc:
      enabled: true
      addr: "0.0.0.0"
      port: 8545
      corsDomain: "*"
      vHosts: "*"
      api: "admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul"  
      authenticationEnabled: false
    ws:
      enabled: true
      addr: "0.0.0.0"
      port: 8546
      api: "admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul"
      origins: "*"
      authenticationEnabled: false
    graphql:
      enabled: true
      addr: "0.0.0.0"
      port: 8547
      corsDomain: "*"
      vHosts: "*"
    metrics:
      enabled: true
      pprofaddr: "0.0.0.0"
      pprofport: 9545
      serviceMonitorEnabled: false
    privacy:
      url: "http://localhost:9101"
      pubkeysPath: "/tessera"
      pubkeyFile: "/tessera/tm.pub"

  tessera:
    resources:
      cpuLimit: 0.7
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    tmkey: ""
    tmpub: ""
    password: "password"
    passwordPath: "/keys/tm.password"
    dataPath: "/data/tessera"
    keysPath: "/keys"
    port: 9000
    tpport: 9080
    q2tport: 9101

image:
  goquorum:
    repository: quorumengineering/quorum
    tag: 24.4
  tessera:
    repository: quorumengineering/tessera
    tag: 24.4
  hooks:
    repository: consensys/quorum-k8s-hooks
    tag: qgt-0.2.18
    pullPolicy: IfNotPresent
