---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "besu.fullname" . }}-validator3-key
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.validators.validator3.privateKey }}
  key: {{ .Values.validators.validator3.privateKey | b64enc }}
  {{- end }}
