{{- $validatorNumber := "validator4" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "besu.fullname" . }}-{{ $validatorNumber }}
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
    component: {{ $validatorNumber }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "besu.name" . }}
      release: {{ .Release.Name }}
      component: {{ $validatorNumber }}
  serviceName: {{ template "besu.fullname" . }}-validator4
  template:
    metadata:
      labels:
        app: {{ template "besu.name" . }}
        release: {{ .Release.Name }}
        component: {{ $validatorNumber }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: init-bootnode
        image: byrnedo/alpine-curl
        command:
          - "sh"
          - "-c"
          - "curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 ${BESU_VALIDATOR1_SERVICE_HOST}:8545/liveness"
      containers:
      - name: {{ $validatorNumber }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: VALIDATOR1_PUBKEY
            valueFrom:
              configMapKeyRef:
                name: besu-configmap-validators
                key: validator1PubKey
          - name: VALIDATOR2_PUBKEY
            valueFrom:
              configMapKeyRef:
                name: besu-configmap-validators
                key: validator2PubKey
        volumeMounts:
          - name: key
            mountPath: /secrets
            readOnly: true
          - name: genesis-config
            mountPath: /etc/genesis
            readOnly: true
          - name: config-toml
            mountPath: /etc/besu
            readOnly: true
          - name: data
            mountPath: /data
        ports:
          - name: http
            containerPort: {{ .Values.besuConfig.rpc.port }}
            protocol: TCP
          - name: ws
            containerPort: {{ .Values.besuConfig.ws.port }}
            protocol: TCP
          - name: graphql
            containerPort: {{ .Values.besuConfig.graphql.port }}
            protocol: TCP
          - name: p2p-tcp
            containerPort: {{ .Values.besuConfig.p2p.port }}
            protocol: TCP
          - name: p2p-udp
            containerPort: {{ .Values.besuConfig.p2p.port }}
            protocol: UDP
          - name: metrics
            containerPort: {{ .Values.besuConfig.metrics.port }}
            protocol: TCP
        command:
          - /bin/sh
          - -c
        args:
          - |
            exec /opt/besu/bin/besu \
              --node-private-key-file=/secrets/key \
              --config-file=/etc/besu/config.toml \
              --bootnodes=enode://${VALIDATOR1_PUBKEY}@${BESU_VALIDATOR1_SERVICE_HOST}:30303,enode://${VALIDATOR2_PUBKEY}@${BESU_VALIDATOR2_SERVICE_HOST}:30303
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: key
        secret:
          secretName: besu-{{ $validatorNumber }}-key
          items:
            - key: {{ $validatorNumber }}Key
              path: key
      - name: genesis-config
        configMap:
          name: besu-configmap-besu-genesis
          items:
            - key: genesis.json
              path: genesis.json
      - name: config-toml
        configMap:
          name: besu-configmap-config-toml
      - name: data
        emptyDir:
          sizeLimit: "{{ .Values.node.pvcSizeLimit }}"
