apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-config-toml-configmap
  labels:
    app: besu-config-toml-configmap
  namespace: besu
data:
  config.toml: |-
    # Every possible CLI should be in this file.
    #
    # Please use a plausible value, besu has to at least be able to parse it.
    # If it is a multi-valued CLI make it a TOML array.
    # If it is a number or boolean make it a number or boolean
    # All other config options are strings, and must be quoted.

    # Node Information
    data-path="/data"
    genesis-file="/etc/genesis/genesis.json"
    # TODO : insert as command line & mount Volume
    # rpc-http-authentication-credentials-file="none"
    # TODO : insert as command line & mount Volume
    # rpc-ws-authentication-credentials-file="none"
    # TODO : insert as command line & mount Volume
    # permissions-nodes-config-file="./permissions_config.toml"
    # TODO : insert as command line & mount Volume
    # permissions-accounts-config-file="./permissions_config.toml"
    logging="INFO"

    # Transaction Pool
    tx-pool-retention-hours=999
    tx-pool-max-size=1024

    # P2P network
    p2p-enabled=true
    discovery-enabled=true
    #p2p-host="0.0.0.0"
    p2p-port=30303
    max-peers=25

    host-allowlist=["*"]

    # JSON-RPC
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=8545
    rpc-http-api=["DEBUG","ETH", "ADMIN", "WEB3", "CLIQUE", "NET"]
    rpc-http-cors-origins=["*"]
    rpc-http-authentication-enabled=false

    # GRAPHQL-RPC
    graphql-http-enabled=false
    graphql-http-host="0.0.0.0"
    graphql-http-port=8547
    graphql-http-cors-origins=["*"]

    # WebSockets API
    rpc-ws-enabled=false
    rpc-ws-host="0.0.0.0"
    rpc-ws-port=8546
    rpc-ws-api=["DEBUG","ETH", "ADMIN", "WEB3", "CLIQUE", "NET"]
    rpc-ws-authentication-enabled=false

    # Metrics
    metrics-enabled=true
    metrics-host="0.0.0.0"
    metrics-port=9545

